### ISSUE TITLE
Decimal fields do not serialize to a json compatible field

### ISSUE THREAD

**Issue by SavvyGuard** [anossov/openrtb#10]
Decimal types do not have a 'serialize' method associated with them, so when serialized, decimal fields in an object just get returned as decimal fields, which do not convert to json properly using the standard json library.

**Comment by anossov** [comment]
I feel this is out of this library's scope, it converts its objects to generic Python dicts, which you are free to then serialize to any format using any encoder implementation. With the standard `json` module, use a custom `default` function or a custom encoder `cls`.

**Comment by SavvyGuard** [comment]
@anossov What's the thinking behind using Decimal for this field? As far as I can tell, Decimal is not used anywhere else, and a float would suffice just as well in this location.

**Comment by anossov** [comment]
`Bid.price` and `Impression.bidfloor` are Decimals because they are used in calculations involving currency, it help avoid certain bugs. Even the OpenRTB standard states

>    Note that while the type indicates float, integer math is highly recommended when handling currencies (e.g., BigDecimal in Java).
